name: 🐞 Bug Report
description: Create a bug report to help us improve. Thank you.
title: "[BUG] "
labels: 
  - bug
assignees: edwinjhlee
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: 💬 Describe the bug
      description: A clear and concise description of what the bug is.

  - type: textarea
    validations:
      required: true
    attributes:
      label: 📄 System
      render: yaml
      description: |
        Output of `x scotty info`<br>
        Provide the version information of the system and X-CMD.
      placeholder: |
        - Version: [A sha512, type 'x version' so you can get the version sum]
        - Shell: [e.g. Dash, Bash, Zsh]
        - OS: [e.g. Linux, Darwin, Windows]
        - Arch: [e.g. amd64, arm64]

  - type: textarea
    attributes:
      label: 🔎 To Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Start up service: `...`
        2. Type command: `...`

        ### Expected behavior
        <!-- A clear and concise description of what you expected to happen. -->

  - type: textarea
    attributes:
      label: 🗂️ Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        Add any other context about the problem here.
        📷 Screenshots or 📹 Screen Recording (if possible).
