name: 💡 Feature Request
description: Ideas to make x-cmd better. Thank you for your attention, star, and support.
title: "[FEATURE] "
labels:
  - enhancement
assignees: edwinjhlee
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: 💭 Describe the feature
      description: What's it for and why you want
      placeholder: A clear and concise description of what the feature is, and what it will enhance or solve.

  - type: dropdown
    validations:
      required: true
    attributes:
      label: ⏰ Is is urgent
      description: |
        We're a small team and may not be able to respond immediately.<br>
        But we value x-cmd and our users greatly, and always do our best.
      multiple: false
      options:
        - 'NO'
        - 'YES'

  - type: textarea
    attributes:
      label: 🗂️ Additional Context
      description: Describe a clear and concise description of what you want to happen.
      placeholder: |
        Describe a clear and concise description of what you want to happen.
        📷 Screenshots or 📹 Screen Recording (if possible).

