name: 📦 Recommendation
description: Supercharge x-cmd with more pkgs and installations recipes.
title: "[REC] "
labels: 
  - install
assignees: edwinjhlee
body:
  - type: input
    validations:
      required: true
    attributes:
      label: 🔗 Website
      description: GitHub repo or homepage
      placeholder: https://github.com/?/?

  - type: dropdown
    validations:
      required: true
    attributes:
      label: 📦 Ready to be included in [x-cmd pkg](https://x-cmd.com/pkg) ?
      multiple: false
      options:
        - 'NO'
        - 'YES'

  - type: textarea
    attributes:
      label: 📥 How to install
      render: shell
      description: '!! We will review and put it into [x install recipes](https://x-cmd.com/install).'
      value: |
        apt install <name>
        scoop install <name>

  - type: textarea
    attributes:
      label: 📝 TLDR
      render: shell
      description: |
        Provide a TLDR like example to help us understand<br>
        Don't hesitate ~ The more the better !!!
      value: |
        # <desc-1>
        <command-1>

        # <desc-2>
        <command-2>

        # <desc-3>
        <command-3>

  - type: textarea
    attributes:
      label: 🌟 Highlights
      description: |
        Help us find the best way to promote this tool to users.<br>
        We will launch it on our official website and channels. 
      value: |
        - Discuss the advantages of this tool.
        - Stories about this tool:
        - Discuss the disadvantages of this tool.
