name: 📚 Suggesting Corrections / Improvements to Article
description: If you've spotted an error in the article, or you'd like to see related articles completed sooner, please feel free to open an issue.
title: "[Doc] "
labels: 
  - article
assignees: Zhengqbbb
body:
  - type: input
    validations:
      required: true
    attributes:
      label: 🔗 URL
      description: Please provide the url here
      placeholder: https://x-cmd.com/?/?
  
  - type: 'textarea'
    validations:
      required: true
    attributes:
      label: 💬 Description
      value: |
        Typos:

        Error:

        Suggestion:

        Request:

  - type: textarea
    attributes:
      label: 🗂️ Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        Add any other context about the problem here.
        📷 Screenshots or 📹 Screen Recording (if possible).