#!/usr/bin/env gawk
# Generate precomputed bitwise tables as literal array assignments

BEGIN {
    print "# Precomputed nibble tables for POSIX awk"
    print "# Generated by gen_tables.awk - DO NOT EDIT"
    print ""

    # nibble_xor[0-255] where index = a*16 + b
    printf "# nibble_xor[a*16+b] = a XOR b (nibble only)\n"
    for (a = 0; a < 16; a++) {
        for (b = 0; b < 16; b++) {
            printf "nibble_xor[%d]=%d ", a*16+b, xor(a, b)
        }
        print ""
    }
    print ""

    # nibble_and
    printf "# nibble_and[a*16+b] = a AND b (nibble only)\n"
    for (a = 0; a < 16; a++) {
        for (b = 0; b < 16; b++) {
            printf "nibble_and[%d]=%d ", a*16+b, and(a, b)
        }
        print ""
    }
    print ""

    # nibble_or
    printf "# nibble_or[a*16+b] = a OR b (nibble only)\n"
    for (a = 0; a < 16; a++) {
        for (b = 0; b < 16; b++) {
            printf "nibble_or[%d]=%d ", a*16+b, or(a, b)
        }
        print ""
    }
    print ""

    # high_nibble[0-255]
    printf "# high_nibble[byte] = byte / 16 (integer division)\n"
    for (byte = 0; byte < 256; byte++) {
        printf "high_nibble[%d]=%d ", byte, int(byte / 16)
    }
    print ""
    print ""

    # low_nibble[0-255]
    printf "# low_nibble[byte] = byte %% 16\n"
    for (byte = 0; byte < 256; byte++) {
        printf "low_nibble[%d]=%d ", byte, byte % 16
    }
    print ""
}
