# ASCII Letter Art - 统一行数以便并排显示
{
# 大写字母 A-Z (5行高度)
local ___X_CMD_ASCII_LETTER_A_01=' ▟██▙ '
local ___X_CMD_ASCII_LETTER_A_02='▟█  █▙'
local ___X_CMD_ASCII_LETTER_A_03='██████'
local ___X_CMD_ASCII_LETTER_A_04='█    █'
local ___X_CMD_ASCII_LETTER_A_05='█    █'

local ___X_CMD_ASCII_LETTER_B_01='█████▙'
local ___X_CMD_ASCII_LETTER_B_02='█    █'
local ___X_CMD_ASCII_LETTER_B_03='█████ '
local ___X_CMD_ASCII_LETTER_B_04='█    █'
local ___X_CMD_ASCII_LETTER_B_05='█████▛'

local ___X_CMD_ASCII_LETTER_C_01='▟████ '
local ___X_CMD_ASCII_LETTER_C_02='█     '
local ___X_CMD_ASCII_LETTER_C_03='█     '
local ___X_CMD_ASCII_LETTER_C_04='█     '
local ___X_CMD_ASCII_LETTER_C_05='▜████ '

local ___X_CMD_ASCII_LETTER_D_01='████▙ '
local ___X_CMD_ASCII_LETTER_D_02='█   █ '
local ___X_CMD_ASCII_LETTER_D_03='█   █ '
local ___X_CMD_ASCII_LETTER_D_04='█   █ '
local ___X_CMD_ASCII_LETTER_D_05='████▛ '

local ___X_CMD_ASCII_LETTER_E_01='█████ '
local ___X_CMD_ASCII_LETTER_E_02='█     '
local ___X_CMD_ASCII_LETTER_E_03='████  '
local ___X_CMD_ASCII_LETTER_E_04='█     '
local ___X_CMD_ASCII_LETTER_E_05='█████ '

local ___X_CMD_ASCII_LETTER_F_01='█████ '
local ___X_CMD_ASCII_LETTER_F_02='█     '
local ___X_CMD_ASCII_LETTER_F_03='████  '
local ___X_CMD_ASCII_LETTER_F_04='█     '
local ___X_CMD_ASCII_LETTER_F_05='█     '

local ___X_CMD_ASCII_LETTER_G_01='▟█████'
local ___X_CMD_ASCII_LETTER_G_02='█     '
local ___X_CMD_ASCII_LETTER_G_03='█  ███'
local ___X_CMD_ASCII_LETTER_G_04='█    █'
local ___X_CMD_ASCII_LETTER_G_05=' █████'

local ___X_CMD_ASCII_LETTER_H_01='█    █'
local ___X_CMD_ASCII_LETTER_H_02='█    █'
local ___X_CMD_ASCII_LETTER_H_03='██████'
local ___X_CMD_ASCII_LETTER_H_04='█    █'
local ___X_CMD_ASCII_LETTER_H_05='█    █'

local ___X_CMD_ASCII_LETTER_I_01='▐████▋'
local ___X_CMD_ASCII_LETTER_I_02='  ▐▋  '
local ___X_CMD_ASCII_LETTER_I_03='  ▐▋  '
local ___X_CMD_ASCII_LETTER_I_04='  ▐▋  '
local ___X_CMD_ASCII_LETTER_I_05='▐████▋'

local ___X_CMD_ASCII_LETTER_J_01='▐████▋'
local ___X_CMD_ASCII_LETTER_J_02='   █  '
local ___X_CMD_ASCII_LETTER_J_03='   █  '
local ___X_CMD_ASCII_LETTER_J_04='▐▋ █  '
local ___X_CMD_ASCII_LETTER_J_05=' ███  '

local ___X_CMD_ASCII_LETTER_K_01='█   █ '
local ___X_CMD_ASCII_LETTER_K_02='█  █  '
local ___X_CMD_ASCII_LETTER_K_03='███   '
local ___X_CMD_ASCII_LETTER_K_04='█  █  '
local ___X_CMD_ASCII_LETTER_K_05='█   █ '

local ___X_CMD_ASCII_LETTER_L_01='█     '
local ___X_CMD_ASCII_LETTER_L_02='█     '
local ___X_CMD_ASCII_LETTER_L_03='█     '
local ___X_CMD_ASCII_LETTER_L_04='█     '
local ___X_CMD_ASCII_LETTER_L_05='█████ '

local ___X_CMD_ASCII_LETTER_M_01='█    █'
local ___X_CMD_ASCII_LETTER_M_02='█▙  ▟█'
local ___X_CMD_ASCII_LETTER_M_03='█ ▐▋ █'
local ___X_CMD_ASCII_LETTER_M_04='█    █'
local ___X_CMD_ASCII_LETTER_M_05='█    █'

local ___X_CMD_ASCII_LETTER_N_01='█    █'
local ___X_CMD_ASCII_LETTER_N_02='█▙   █'
local ___X_CMD_ASCII_LETTER_N_03='█ ▐▋ █'
local ___X_CMD_ASCII_LETTER_N_04='█   ▜█'
local ___X_CMD_ASCII_LETTER_N_05='█    █'

local ___X_CMD_ASCII_LETTER_O_01=' ▟██▙ '
local ___X_CMD_ASCII_LETTER_O_02='█    █'
local ___X_CMD_ASCII_LETTER_O_03='█    █'
local ___X_CMD_ASCII_LETTER_O_04='█    █'
local ___X_CMD_ASCII_LETTER_O_05=' ▜██▛ '

local ___X_CMD_ASCII_LETTER_P_01='█████▙'
local ___X_CMD_ASCII_LETTER_P_02='█    █'
local ___X_CMD_ASCII_LETTER_P_03='█████▛'
local ___X_CMD_ASCII_LETTER_P_04='█     '
local ___X_CMD_ASCII_LETTER_P_05='█     '

local ___X_CMD_ASCII_LETTER_Q_01=' ▟██▙ '
local ___X_CMD_ASCII_LETTER_Q_02='█    █'
local ___X_CMD_ASCII_LETTER_Q_03='█    █'
local ___X_CMD_ASCII_LETTER_Q_04='█   ▜▙'
local ___X_CMD_ASCII_LETTER_Q_05=' ▜██ █'

local ___X_CMD_ASCII_LETTER_R_01='█████▙'
local ___X_CMD_ASCII_LETTER_R_02='█    █'
local ___X_CMD_ASCII_LETTER_R_03='█████▛'
local ___X_CMD_ASCII_LETTER_R_04='█  ▜▙ '
local ___X_CMD_ASCII_LETTER_R_05='█   ▜▙'

local ___X_CMD_ASCII_LETTER_S_01='▟███▙ '
local ___X_CMD_ASCII_LETTER_S_02='█     '
local ___X_CMD_ASCII_LETTER_S_03=' ███▙ '
local ___X_CMD_ASCII_LETTER_S_04='    █ '
local ___X_CMD_ASCII_LETTER_S_05='▜███▛ '

local ___X_CMD_ASCII_LETTER_T_01='██████'
local ___X_CMD_ASCII_LETTER_T_02='  ▐▋  '
local ___X_CMD_ASCII_LETTER_T_03='  ▐▋  '
local ___X_CMD_ASCII_LETTER_T_04='  ▐▋  '
local ___X_CMD_ASCII_LETTER_T_05='  ▐▋  '

local ___X_CMD_ASCII_LETTER_U_01='█    █'
local ___X_CMD_ASCII_LETTER_U_02='█    █'
local ___X_CMD_ASCII_LETTER_U_03='█    █'
local ___X_CMD_ASCII_LETTER_U_04='█    █'
local ___X_CMD_ASCII_LETTER_U_05=' ▜██▛ '

local ___X_CMD_ASCII_LETTER_V_01='█    █'
local ___X_CMD_ASCII_LETTER_V_02='█    █'
local ___X_CMD_ASCII_LETTER_V_03='█    █'
local ___X_CMD_ASCII_LETTER_V_04=' █  █ '
local ___X_CMD_ASCII_LETTER_V_05='  ▀▀  '

local ___X_CMD_ASCII_LETTER_W_01='█    █'
local ___X_CMD_ASCII_LETTER_W_02='█    █'
local ___X_CMD_ASCII_LETTER_W_03='█ ██ █'
local ___X_CMD_ASCII_LETTER_W_04='██  ██'
local ___X_CMD_ASCII_LETTER_W_05='█    █'

local ___X_CMD_ASCII_LETTER_X_01='█    █'
local ___X_CMD_ASCII_LETTER_X_02=' █  █ '
local ___X_CMD_ASCII_LETTER_X_03='  ██  '
local ___X_CMD_ASCII_LETTER_X_04=' █  █ '
local ___X_CMD_ASCII_LETTER_X_05='█    █'

local ___X_CMD_ASCII_LETTER_Y_01='█    █'
local ___X_CMD_ASCII_LETTER_Y_02=' █  █ '
local ___X_CMD_ASCII_LETTER_Y_03='  ██  '
local ___X_CMD_ASCII_LETTER_Y_04='  ▐▋  '
local ___X_CMD_ASCII_LETTER_Y_05='  ▐▋  '

local ___X_CMD_ASCII_LETTER_Z_01='█████ '
local ___X_CMD_ASCII_LETTER_Z_02='   █  '
local ___X_CMD_ASCII_LETTER_Z_03='  █   '
local ___X_CMD_ASCII_LETTER_Z_04=' █    '
local ___X_CMD_ASCII_LETTER_Z_05='█████ '

# 阿拉伯数字 0-9 (7段数码管风格, 5行高度)
local ___X_CMD_ASCII_LETTER_0_01='█████ '
local ___X_CMD_ASCII_LETTER_0_02='█   █ '
local ___X_CMD_ASCII_LETTER_0_03='█   █ '
local ___X_CMD_ASCII_LETTER_0_04='█   █ '
local ___X_CMD_ASCII_LETTER_0_05='█████ '

local ___X_CMD_ASCII_LETTER_1_01='  █   '
local ___X_CMD_ASCII_LETTER_1_02='  █   '
local ___X_CMD_ASCII_LETTER_1_03='  █   '
local ___X_CMD_ASCII_LETTER_1_04='  █   '
local ___X_CMD_ASCII_LETTER_1_05='  █   '

local ___X_CMD_ASCII_LETTER_2_01='█████ '
local ___X_CMD_ASCII_LETTER_2_02='    █ '
local ___X_CMD_ASCII_LETTER_2_03='█████ '
local ___X_CMD_ASCII_LETTER_2_04='█     '
local ___X_CMD_ASCII_LETTER_2_05='█████ '

local ___X_CMD_ASCII_LETTER_3_01='█████ '
local ___X_CMD_ASCII_LETTER_3_02='    █ '
local ___X_CMD_ASCII_LETTER_3_03='█████ '
local ___X_CMD_ASCII_LETTER_3_04='    █ '
local ___X_CMD_ASCII_LETTER_3_05='█████ '

local ___X_CMD_ASCII_LETTER_4_01='█   █ '
local ___X_CMD_ASCII_LETTER_4_02='█   █ '
local ___X_CMD_ASCII_LETTER_4_03='█████ '
local ___X_CMD_ASCII_LETTER_4_04='    █ '
local ___X_CMD_ASCII_LETTER_4_05='    █ '

local ___X_CMD_ASCII_LETTER_5_01='█████ '
local ___X_CMD_ASCII_LETTER_5_02='█     '
local ___X_CMD_ASCII_LETTER_5_03='█████ '
local ___X_CMD_ASCII_LETTER_5_04='    █ '
local ___X_CMD_ASCII_LETTER_5_05='█████ '

local ___X_CMD_ASCII_LETTER_6_01='█████ '
local ___X_CMD_ASCII_LETTER_6_02='█     '
local ___X_CMD_ASCII_LETTER_6_03='█████ '
local ___X_CMD_ASCII_LETTER_6_04='█   █ '
local ___X_CMD_ASCII_LETTER_6_05='█████ '

local ___X_CMD_ASCII_LETTER_7_01='█████ '
local ___X_CMD_ASCII_LETTER_7_02='    █ '
local ___X_CMD_ASCII_LETTER_7_03='    █ '
local ___X_CMD_ASCII_LETTER_7_04='    █ '
local ___X_CMD_ASCII_LETTER_7_05='    █ '

local ___X_CMD_ASCII_LETTER_8_01='█████ '
local ___X_CMD_ASCII_LETTER_8_02='█   █ '
local ___X_CMD_ASCII_LETTER_8_03='█████ '
local ___X_CMD_ASCII_LETTER_8_04='█   █ '
local ___X_CMD_ASCII_LETTER_8_05='█████ '

local ___X_CMD_ASCII_LETTER_9_01='█████ '
local ___X_CMD_ASCII_LETTER_9_02='█   █ '
local ___X_CMD_ASCII_LETTER_9_03='█████ '
local ___X_CMD_ASCII_LETTER_9_04='    █ '
local ___X_CMD_ASCII_LETTER_9_05='█████ '

# 标点符号 (5行高度)
local ___X_CMD_ASCII_LETTER_MINUS_01='      '
local ___X_CMD_ASCII_LETTER_MINUS_02='      '
local ___X_CMD_ASCII_LETTER_MINUS_03=' ███  '
local ___X_CMD_ASCII_LETTER_MINUS_04='      '
local ___X_CMD_ASCII_LETTER_MINUS_05='      '

local ___X_CMD_ASCII_LETTER_UNDERSCORE_01='      '
local ___X_CMD_ASCII_LETTER_UNDERSCORE_02='      '
local ___X_CMD_ASCII_LETTER_UNDERSCORE_03='      '
local ___X_CMD_ASCII_LETTER_UNDERSCORE_04='      '
local ___X_CMD_ASCII_LETTER_UNDERSCORE_05='█████ '

local ___X_CMD_ASCII_LETTER_COLON_01='      '
local ___X_CMD_ASCII_LETTER_COLON_02='  █   '
local ___X_CMD_ASCII_LETTER_COLON_03='      '
local ___X_CMD_ASCII_LETTER_COLON_04='  █   '
local ___X_CMD_ASCII_LETTER_COLON_05='      '

local ___X_CMD_ASCII_LETTER_SPACE_01='      '
local ___X_CMD_ASCII_LETTER_SPACE_02='      '
local ___X_CMD_ASCII_LETTER_SPACE_03='      '
local ___X_CMD_ASCII_LETTER_SPACE_04='      '
local ___X_CMD_ASCII_LETTER_SPACE_05='      '

local ___X_CMD_ASCII_LETTER_DOT_01='      '
local ___X_CMD_ASCII_LETTER_DOT_02='      '
local ___X_CMD_ASCII_LETTER_DOT_03='      '
local ___X_CMD_ASCII_LETTER_DOT_04='      '
local ___X_CMD_ASCII_LETTER_DOT_05='  ██  '

local ___X_CMD_ASCII_LETTER_COMMA_01='      '
local ___X_CMD_ASCII_LETTER_COMMA_02='      '
local ___X_CMD_ASCII_LETTER_COMMA_03='      '
local ___X_CMD_ASCII_LETTER_COMMA_04='  █   '
local ___X_CMD_ASCII_LETTER_COMMA_05=' █    '

local ___X_CMD_ASCII_LETTER_EXCLAMATION_01='  █   '
local ___X_CMD_ASCII_LETTER_EXCLAMATION_02='  █   '
local ___X_CMD_ASCII_LETTER_EXCLAMATION_03='  █   '
local ___X_CMD_ASCII_LETTER_EXCLAMATION_04='      '
local ___X_CMD_ASCII_LETTER_EXCLAMATION_05='  █   '

local ___X_CMD_ASCII_LETTER_QUESTION_01=' ███  '
local ___X_CMD_ASCII_LETTER_QUESTION_02='█   █ '
local ___X_CMD_ASCII_LETTER_QUESTION_03='   █  '
local ___X_CMD_ASCII_LETTER_QUESTION_04='      '
local ___X_CMD_ASCII_LETTER_QUESTION_05='  █   '

local ___X_CMD_ASCII_LETTER_SLASH_01='    █ '
local ___X_CMD_ASCII_LETTER_SLASH_02='   █  '
local ___X_CMD_ASCII_LETTER_SLASH_03='  █   '
local ___X_CMD_ASCII_LETTER_SLASH_04=' █    '
local ___X_CMD_ASCII_LETTER_SLASH_05='█     '

local ___X_CMD_ASCII_LETTER_PLUS_01='      '
local ___X_CMD_ASCII_LETTER_PLUS_02='  █   '
local ___X_CMD_ASCII_LETTER_PLUS_03='█████ '
local ___X_CMD_ASCII_LETTER_PLUS_04='  █   '
local ___X_CMD_ASCII_LETTER_PLUS_05='      '

local ___X_CMD_ASCII_LETTER_EQUAL_01='      '
local ___X_CMD_ASCII_LETTER_EQUAL_02='█████ '
local ___X_CMD_ASCII_LETTER_EQUAL_03='      '
local ___X_CMD_ASCII_LETTER_EQUAL_04='█████ '
local ___X_CMD_ASCII_LETTER_EQUAL_05='      '

local ___X_CMD_ASCII_LETTER_LPAREN_01='  ██  '
local ___X_CMD_ASCII_LETTER_LPAREN_02=' █    '
local ___X_CMD_ASCII_LETTER_LPAREN_03='█     '
local ___X_CMD_ASCII_LETTER_LPAREN_04=' █    '
local ___X_CMD_ASCII_LETTER_LPAREN_05='  ██  '

local ___X_CMD_ASCII_LETTER_RPAREN_01='  ██  '
local ___X_CMD_ASCII_LETTER_RPAREN_02='    █ '
local ___X_CMD_ASCII_LETTER_RPAREN_03='     █'
local ___X_CMD_ASCII_LETTER_RPAREN_04='    █ '
local ___X_CMD_ASCII_LETTER_RPAREN_05='  ██  '

local ___X_CMD_ASCII_LETTER_LBRACKET_01=' ███  '
local ___X_CMD_ASCII_LETTER_LBRACKET_02=' █    '
local ___X_CMD_ASCII_LETTER_LBRACKET_03=' █    '
local ___X_CMD_ASCII_LETTER_LBRACKET_04=' █    '
local ___X_CMD_ASCII_LETTER_LBRACKET_05=' ███  '

local ___X_CMD_ASCII_LETTER_RBRACKET_01='  ███ '
local ___X_CMD_ASCII_LETTER_RBRACKET_02='    █ '
local ___X_CMD_ASCII_LETTER_RBRACKET_03='    █ '
local ___X_CMD_ASCII_LETTER_RBRACKET_04='    █ '
local ___X_CMD_ASCII_LETTER_RBRACKET_05='  ███ '

local ___X_CMD_ASCII_LETTER_HASH_01='█ █   '
local ___X_CMD_ASCII_LETTER_HASH_02='█████ '
local ___X_CMD_ASCII_LETTER_HASH_03='█ █   '
local ___X_CMD_ASCII_LETTER_HASH_04='█████ '
local ___X_CMD_ASCII_LETTER_HASH_05='█ █   '

local ___X_CMD_ASCII_LETTER_PERCENT_01='█   █ '
local ___X_CMD_ASCII_LETTER_PERCENT_02='   █  '
local ___X_CMD_ASCII_LETTER_PERCENT_03='  █   '
local ___X_CMD_ASCII_LETTER_PERCENT_04=' █    '
local ___X_CMD_ASCII_LETTER_PERCENT_05='█   █ '

local ___X_CMD_ASCII_LETTER_DOLLAR_01=' ████ '
local ___X_CMD_ASCII_LETTER_DOLLAR_02='█     '
local ___X_CMD_ASCII_LETTER_DOLLAR_03=' ████ '
local ___X_CMD_ASCII_LETTER_DOLLAR_04='    █ '
local ___X_CMD_ASCII_LETTER_DOLLAR_05='█████ '

local ___X_CMD_ASCII_LETTER_AMPERSAND_01='  ██  '
local ___X_CMD_ASCII_LETTER_AMPERSAND_02=' █  █ '
local ___X_CMD_ASCII_LETTER_AMPERSAND_03=' ████ '
local ___X_CMD_ASCII_LETTER_AMPERSAND_04=' █  █ '
local ___X_CMD_ASCII_LETTER_AMPERSAND_05='  ▜▙  '

local ___X_CMD_ASCII_LETTER_ASTERISK_01='  █   '
local ___X_CMD_ASCII_LETTER_ASTERISK_02='█ █ █ '
local ___X_CMD_ASCII_LETTER_ASTERISK_03=' ███  '
local ___X_CMD_ASCII_LETTER_ASTERISK_04='█ █ █ '
local ___X_CMD_ASCII_LETTER_ASTERISK_05='  █   '

local ___X_CMD_ASCII_LETTER_AT_01=' ████ '
local ___X_CMD_ASCII_LETTER_AT_02='█    █'
local ___X_CMD_ASCII_LETTER_AT_03='█ at █'
local ___X_CMD_ASCII_LETTER_AT_04='█     '
local ___X_CMD_ASCII_LETTER_AT_05=' ████ '

local ___X_CMD_ASCII_LETTER_PIPE_01='  █   '
local ___X_CMD_ASCII_LETTER_PIPE_02='  █   '
local ___X_CMD_ASCII_LETTER_PIPE_03='  █   '
local ___X_CMD_ASCII_LETTER_PIPE_04='  █   '
local ___X_CMD_ASCII_LETTER_PIPE_05='  █   '

local ___X_CMD_ASCII_LETTER_BSLASH_01='█     '
local ___X_CMD_ASCII_LETTER_BSLASH_02=' █    '
local ___X_CMD_ASCII_LETTER_BSLASH_03='  █   '
local ___X_CMD_ASCII_LETTER_BSLASH_04='   █  '
local ___X_CMD_ASCII_LETTER_BSLASH_05='    █ '

local ___X_CMD_ASCII_LETTER_CARET_01='  ██  '
local ___X_CMD_ASCII_LETTER_CARET_02=' █  █ '
local ___X_CMD_ASCII_LETTER_CARET_03='      '
local ___X_CMD_ASCII_LETTER_CARET_04='      '
local ___X_CMD_ASCII_LETTER_CARET_05='      '

local ___X_CMD_ASCII_LETTER_GRAVE_01='█     '
local ___X_CMD_ASCII_LETTER_GRAVE_02=' █    '
local ___X_CMD_ASCII_LETTER_GRAVE_03='      '
local ___X_CMD_ASCII_LETTER_GRAVE_04='      '
local ___X_CMD_ASCII_LETTER_GRAVE_05='      '

local ___X_CMD_ASCII_LETTER_TILDE_01='      '
local ___X_CMD_ASCII_LETTER_TILDE_02=' █ ██ '
local ___X_CMD_ASCII_LETTER_TILDE_03='██ █  '
local ___X_CMD_ASCII_LETTER_TILDE_04='      '
local ___X_CMD_ASCII_LETTER_TILDE_05='      '

local ___X_CMD_ASCII_LETTER_QUOTE_01='  █   '
local ___X_CMD_ASCII_LETTER_QUOTE_02='  █   '
local ___X_CMD_ASCII_LETTER_QUOTE_03='      '
local ___X_CMD_ASCII_LETTER_QUOTE_04='      '
local ___X_CMD_ASCII_LETTER_QUOTE_05='      '

local ___X_CMD_ASCII_LETTER_DQUOTE_01=' █ █  '
local ___X_CMD_ASCII_LETTER_DQUOTE_02=' █ █  '
local ___X_CMD_ASCII_LETTER_DQUOTE_03='      '
local ___X_CMD_ASCII_LETTER_DQUOTE_04='      '
local ___X_CMD_ASCII_LETTER_DQUOTE_05='      '

local ___X_CMD_ASCII_LETTER_LT_01='   █  '
local ___X_CMD_ASCII_LETTER_LT_02='  █   '
local ___X_CMD_ASCII_LETTER_LT_03=' █    '
local ___X_CMD_ASCII_LETTER_LT_04='  █   '
local ___X_CMD_ASCII_LETTER_LT_05='   █  '

local ___X_CMD_ASCII_LETTER_GT_01=' █    '
local ___X_CMD_ASCII_LETTER_GT_02='  █   '
local ___X_CMD_ASCII_LETTER_GT_03='   █  '
local ___X_CMD_ASCII_LETTER_GT_04='  █   '
local ___X_CMD_ASCII_LETTER_GT_05=' █    '

local ___X_CMD_ASCII_LETTER_LBRACE_01='  ██  '
local ___X_CMD_ASCII_LETTER_LBRACE_02=' █    '
local ___X_CMD_ASCII_LETTER_LBRACE_03='██    '
local ___X_CMD_ASCII_LETTER_LBRACE_04=' █    '
local ___X_CMD_ASCII_LETTER_LBRACE_05='  ██  '

local ___X_CMD_ASCII_LETTER_RBRACE_01='  ██  '
local ___X_CMD_ASCII_LETTER_RBRACE_02='    █ '
local ___X_CMD_ASCII_LETTER_RBRACE_03='    ██'
local ___X_CMD_ASCII_LETTER_RBRACE_04='    █ '
local ___X_CMD_ASCII_LETTER_RBRACE_05='  ██  '

local ___X_CMD_ASCII_LETTER_SEMICOLON_01='  █   '
local ___X_CMD_ASCII_LETTER_SEMICOLON_02='  █   '
local ___X_CMD_ASCII_LETTER_SEMICOLON_03='      '
local ___X_CMD_ASCII_LETTER_SEMICOLON_04='  █   '
local ___X_CMD_ASCII_LETTER_SEMICOLON_05=' █    '

} 2>/dev/null
