name: update x-cmd/x-cmd release package
on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'version tag'
        required: false
  # schedule:
  # - cron: '10 22 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ___X_CMD_GHACTION_X: x2
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      gh_action_next: ""
      CONCURRENCY: 10
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      CB_TOKEN: ${{ secrets.CB_TOKEN }}
      INPUTS_VERSION_TAG: ${{ github.event.inputs.version-tag }}
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws create-x-cmd-release